#
###################################
# Site wide configuration
####################################
#
title: 오늘따라유난히
email: younhwan1997@naver.com
description: Student. Study Android
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 조윤환
  avatar: avatar.png
  job: "Student"
  bio: "안드로이드 개발자가 되기 위해 공부하고 있습니다."
  email: younhwan1997@naver.com
  disqus-shortname: younhwan-blog
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: younhwan97
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: yh__._.z
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
